FOO-20
ognevoydev/Quisell pull request #10
Opened 2023-01-09 10:31 UTC by ognevoydev

Добавил Docker с postgres и keycloak

2023-01-09 10:36 UTC, ognevoydev commented on docker-compose.yaml
> +    environment:
еще есть quay.io/keycloak, но пишут что между ним и jboss/keycloak нет разницы

2023-01-09 16:54 UTC, TiPo4u4eK commented on docker-compose.yaml
> +    environment:
jboss до 16.1.1 quay следующие

2023-01-09 17:01 UTC, TiPo4u4eK requested changes

2023-01-12 12:32 UTC, ognevoydev commented on docker-compose.yaml
> +    environment:
если ставлю quay контейнер останавливается с ошибкой. с jboss 16.1.1 всё норм

2023-01-12 18:00 UTC, TiPo4u4eK requested changes

2023-01-12 18:00 UTC, TiPo4u4eK commented on docker-compose.yaml
> +      DB_VENDOR: h2
можно убрать

2023-01-14 17:33 UTC, TiPo4u4eK approved these changes

2023-01-14 17:33 UTC, merged