FOO-29: unit tests for service
ognevoydev/Quisell pull request #14
Opened 2023-01-18 17:04 UTC by ognevoydev

Написал тесты для сервиса

2023-01-19 13:55 UTC, TiPo4u4eK requested changes

2023-01-21 00:58 UTC, TiPo4u4eK requested changes

2023-01-25 12:58 UTC, ognevoydev commented on src/test/java/com/ognevoydev/quisell/service/PostServiceImplTest.java
> +
Касательно удаления, может лучше сделать, чтобы в списке всех постов возвращались только не удалённые? И оставить возможность просмотра удаленного только по его id. Не вижу смысла оставлять удалённые посты в ленте объявлений.

2023-02-04 09:17 UTC, TiPo4u4eK approved these changes

2023-02-04 09:17 UTC, merged