FOO-31
ognevoydev/Quisell pull request #9
Opened 2023-01-09 10:01 UTC by ognevoydev

Добавил Swagger

2023-01-09 10:34 UTC, ognevoydev commented on pom.xml
swagger-ui открывается в браузере только с wbmvc стартером. если использовать только core, ui и security, выдаёт 404

2023-01-09 18:29 UTC, TiPo4u4eK commented on pom.xml
https://springdoc.org/v2/#migrating-from-springdoc-v1

2023-01-09 18:42 UTC, TiPo4u4eK requested changes

2023-01-09 18:42 UTC, TiPo4u4eK commented on src/main/java/com/ognevoydev/quisell/config/OpenApiConfig.java
> +}
Добавь GroupedOpenApi чтобы почище выглядел swagger ui, можно packagesToScan убрать тогда

2023-01-09 18:42 UTC, TiPo4u4eK commented on src/main/java/com/ognevoydev/quisell/controller/PostController.java
> +    @ApiResponse(responseCode = "200", description = "Запрос выполнен успешно")
объедини в ApiResponses

2023-01-09 18:42 UTC, TiPo4u4eK commented on src/main/java/com/ognevoydev/quisell/controller/PostController.java
> +    @ApiResponse(responseCode = "404", description = "Не найдено")
description лучше чтобы соответствовал строковому представлению ответа Post with id {id} not found

2023-01-11 19:54 UTC, TiPo4u4eK requested changes

2023-01-11 19:54 UTC, TiPo4u4eK commented on src/main/java/com/ognevoydev/quisell/config/OpenApiConfig.java
> +    GroupedOpenApi quisellApi() {
Это не работает сейчас
1 - сделай класс публичный
2 - исправь разные названия класса и файла
2 - у тебя не создаётся quisellApi т.к. для этого не хватает чтобы создавался бин класса конфига

2023-01-11 19:54 UTC, TiPo4u4eK commented on src/main/java/com/ognevoydev/quisell/config/OpenApiConfig.java
> +                .packagesToScan("com.ognevoydev.quisell")
допиши .displayName("Quisell user API")

2023-01-11 19:54 UTC, TiPo4u4eK commented on src/main/java/com/ognevoydev/quisell/config/OpenApiConfig.java
> +class OpenAPIConfig {
SwaggerConfig

2023-01-11 19:54 UTC, TiPo4u4eK commented on src/main/java/com/ognevoydev/quisell/config/OpenApiConfig.java
> +                .group("quisell")
.group("user")

2023-01-12 18:03 UTC, TiPo4u4eK commented on src/main/java/com/ognevoydev/quisell/config/SwaggerConfig.java
> +    public OpenAPI openApi() {
Можно было аннотацией оставить, но ладно

2023-01-12 18:03 UTC, TiPo4u4eK approved these changes

2023-01-14 15:38 UTC, ognevoydev commented on src/main/java/com/ognevoydev/quisell/config/SwaggerConfig.java
> +    public OpenAPI openApi() {
исправил, можно сливать

2023-01-14 17:31 UTC, merged